
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author thayrone
 */
public class TelaInicial extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        pFuncionario.setVisible(false);
        pAluno.setVisible(false);
        pProfessor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnIdade = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lbSexo = new javax.swing.JComboBox<>();
        pFuncionario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cSetor = new javax.swing.JComboBox<>();
        btnTrabalhando = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        tbSalario = new javax.swing.JTextField();
        pAluno = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbMatricula = new javax.swing.JTextField();
        rBolsista = new javax.swing.JRadioButton();
        cbCurso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        pProfessor = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbEspecialidade = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tbSalarioProfessor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de pessoas");

        jLabel1.setText("Cadastro:");

        jLabel2.setText("Tipo:");

        lbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visitante", "Funcionário", "Aluno", "Professor" }));
        lbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Sexo:");

        lbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prefiro não informar", "Masculino", "Feminino", "Não binario", "Outro" }));

        pFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Setor: ");
        pFuncionario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        cSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Financeiro", "RH", "Comercial", "Operaciona" }));
        pFuncionario.add(cSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 6, 249, -1));

        btnTrabalhando.setText("Trabalhando");
        pFuncionario.add(btnTrabalhando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel11.setText("Salario:");
        pFuncionario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        pFuncionario.add(tbSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 240, -1));

        pAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Matricula:");
        pAluno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel7.setText("Curso:");
        pAluno.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));
        pAluno.add(tbMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, 214, -1));

        rBolsista.setText("Bolsista");
        rBolsista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBolsistaActionPerformed(evt);
            }
        });
        pAluno.add(rBolsista, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 89, -1, -1));

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lógica", "Python", "Node.JS", "PHP", "Javascript", "Java", ".NET", "Jogos", "Computação", "Dart", "Elixir", "Kotlin" }));
        pAluno.add(cbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 46, 214, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Especialidade");
        pProfessor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        cbEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engenharia da computação", "Programação", "Logica e algoritmo", " ", " " }));
        pProfessor.add(cbEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 6, 190, -1));

        jLabel10.setText("Salario");
        pProfessor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));
        pProfessor.add(tbSalarioProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 46, 190, -1));

        jLabel12.setText("Lista cadastros");

        jScrollPane4.setViewportView(Lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spnIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTipoActionPerformed

        if (null == lbTipo.getSelectedItem().toString()) {
            pFuncionario.setVisible(false);
            pAluno.setVisible(false);
            pProfessor.setVisible(false);
        } else // TODO add your handling code here:
            switch (lbTipo.getSelectedItem().toString()) {
                case "Aluno" -> {
                    pAluno.setVisible(true);
                    pFuncionario.setVisible(false);
                    pProfessor.setVisible(false);
                }
                case "Funcionário" -> {
                    pFuncionario.setVisible(true);
                    pAluno.setVisible(false);
                    pProfessor.setVisible(false);
                }
                case "Professor" -> {
                    pFuncionario.setVisible(false);
                    pAluno.setVisible(false);
                    pProfessor.setVisible(true);
                }
                default -> {
                    pFuncionario.setVisible(false);
                    pAluno.setVisible(false);
                    pProfessor.setVisible(false);
                }
            }
    }//GEN-LAST:event_lbTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Conexao.conectar();
        Conexao.desconectar();
        Metodos m = new Metodos();
        if (null == lbTipo.getSelectedItem().toString()) {

        } else // TODO add your handling code here:
            switch (lbTipo.getSelectedItem().toString()) {
                case "Aluno" -> {
                    int tipo = 0;
                 
                    if (rBolsista.isSelected()) {
                        System.out.println("veio até aqui dentro do if");
                        tipo = 1;
                    }
                    System.out.println("veio até aqui fora do if");
                    m.criaAluno(tipo, Integer.parseInt(tbMatricula.getText()), cbCurso.getSelectedItem().toString(), tbNome.getText(), Integer.parseInt(spnIdade.getValue().toString()), lbSexo.getSelectedItem().toString());
            
                   // for (int i = 0; i < m.a.size(); i++) {
                        model.addElement(m.f.get(0).info());
                        System.out.println("veio até aqui");
                    //}
                    Lista.setModel(model);

                }
                case "Funcionário" -> {
                    m.criaFuncionario(cSetor.getSelectedItem().toString(), btnTrabalhando.isSelected(), Float.parseFloat(tbSalario.getText()), tbNome.getText(), (Integer) spnIdade.getValue(), lbSexo.getSelectedItem().toString());
                    for (int i = 0; i < m.f.size(); i++) {
                        model.addElement(m.f.get(i).info());
                    }
                    Lista.setModel(model);

                }
                case "Professor" -> {
                    m.criaProfessor(cbEspecialidade.getSelectedItem().toString(), Float.parseFloat(tbSalarioProfessor.getText()), tbNome.getText(), (Integer) spnIdade.getValue(), lbSexo.getSelectedItem().toString());
                    for (int i = 0; i < m.f.size(); i++) {
                        model.addElement(m.p.get(i).info());
                    }
                    Lista.setModel(model);

                }
                case "Visitante" -> {
                    m.criaVisitante(tbNome.getText(), (Integer) spnIdade.getValue(), lbSexo.getSelectedItem().toString());
                    for (int i = 0; i < m.v.size(); i++) {
                        model.addElement(m.v.get(i).info());
                    }
                    Lista.setModel(model);

                }
                default -> {

                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rBolsistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBolsistaActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_rBolsistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JToggleButton btnTrabalhando;
    private javax.swing.JComboBox<String> cSetor;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbEspecialidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> lbSexo;
    private javax.swing.JComboBox<String> lbTipo;
    private javax.swing.JPanel pAluno;
    private javax.swing.JPanel pFuncionario;
    private javax.swing.JPanel pProfessor;
    private javax.swing.JRadioButton rBolsista;
    private javax.swing.JSpinner spnIdade;
    private javax.swing.JTextField tbMatricula;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbSalario;
    private javax.swing.JTextField tbSalarioProfessor;
    // End of variables declaration//GEN-END:variables
}
